spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: shorturl
      password: 1234

---
server:
  port: 8090
spring:
  config:
    activate:
      on-profile: dev1

---
server:
  port: 8091
spring:
  config:
    activate:
      on-profile: dev2

---
server:
  port: 8092
spring:
  config:
    activate:
      on-profile: prod1

---
server:
  port: 8093
spring:
  config:
    activate:
      on-profile: prod2