# default
server:
  port: 8090

#spring:
#  data:
#    mongodb:
#      uri: mongodb://127.0.0.1:27017
#      database: Study-SpringBoot

---
server:
  port: 8090
spring:
  config:
    activate:
      on-profile: set1

---
server:
  port: 8091
spring:
  config:
    activate:
      on-profile: set2